include /data/nginx/hyrovi-security/blocked-ips.conf;
include conf.d/include/hyrovi_sec_challenge.conf;
add_header       X-Served-By $host;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-Scheme $x_forwarded_scheme;
proxy_set_header X-Forwarded-Proto  $x_forwarded_proto;
proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
proxy_set_header X-Real-IP          $remote_addr;
proxy_set_header X-Hyrovi-Request-ID $request_id;
proxy_set_header X-Hyrovi-Sec-Internal "";
proxy_set_header X-Hyrovi-Sec-Source-IP "";
proxy_set_header X-Hyrovi-Sec-Original-URI "";
proxy_pass       $forward_scheme://$server:$port$request_uri;

