  location {{ path }} {
    include /data/nginx/hyrovi-security/blocked-ips.conf;
    include conf.d/include/hyrovi_sec_challenge.conf;
    {{ advanced_config }}

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto  $scheme;
    proxy_set_header X-Forwarded-For    $remote_addr;
    proxy_set_header X-Real-IP		$remote_addr;
    proxy_set_header X-Hyrovi-Request-ID $request_id;
proxy_set_header X-Hyrovi-Sec-Internal "";
proxy_set_header X-Hyrovi-Sec-Source-IP "";
proxy_set_header X-Hyrovi-Sec-Original-URI "";

    proxy_pass       {{ forward_scheme }}://{{ forward_host }}:{{ forward_port }}{{ forward_path }};

    {% include "_access.conf" %}
    {% include "_assets.conf" %}
    {% include "_exploits.conf" %}
    {% include "_forced_ssl.conf" %}
    {% include "_hsts.conf" %}

    {% if allow_websocket_upgrade == 1 or allow_websocket_upgrade == true %}
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_http_version 1.1;
    {% endif %}
  }

